version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./:/var/www
    networks:
      - laravel_app_default
    depends_on:
      - db-master
    ports:
      - "8090:8090"
    restart: unless-stopped
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db-master
      DB_PORT: 3306
      DB_DATABASE: laravel-app
      DB_USERNAME: root
      DB_PASSWORD: root

  webserver:
    image: nginx:alpine
    container_name: nginx_server
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.      docker-compose down -vconf
    ports:
      - "8081:80"
    networks:
      - laravel_app_default
    depends_on:
      - app

  db-master:
    image: mysql:8.0
    container_name: mysql_master
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel-app
      MYSQL_PASSWORD: root
      MYSQL_REPLICATION_USER: repl
      MYSQL_REPLICATION_PASSWORD: replpass
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=laravel-app
    volumes:
      - dbmasterdata:/var/lib/mysql
      - ./.docker/mysql-init/master-init.sh:/docker-entrypoint-initdb.d/master-init.sh:ro
    ports:
      - "3307:3306"
    networks:
      - laravel_app_default

  db-slave1:
    image: mysql:8.0
    container_name: mysql_slave1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel-app
      MYSQL_PASSWORD: root
      MYSQL_REPLICATION_USER: repl
      MYSQL_REPLICATION_PASSWORD: replpass
      MYSQL_MASTER_HOST: db-master
      MYSQL_MASTER_PORT: 3306
    command: --server-id=2 --relay-log=relay-log-bin --log-bin=mysql-bin --binlog-do-db=laravel-app
    depends_on:
      - db-master
    volumes:
      - dbslave1data:/var/lib/mysql
      - ./.docker/mysql-init/slave-init.sh:/docker-entrypoint-initdb.d/slave-init.sh:ro
    networks:
      - laravel_app_default

  db-slave2:
    image: mysql:8.0
    container_name: mysql_slave2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel-app
      MYSQL_PASSWORD: root
      MYSQL_REPLICATION_USER: repl
      MYSQL_REPLICATION_PASSWORD: replpass
      MYSQL_MASTER_HOST: db-master
      MYSQL_MASTER_PORT: 3306
    command: --server-id=3 --relay-log=relay-log-bin --log-bin=mysql-bin --binlog-do-db=laravel-app
    depends_on:
      - db-master
    volumes:
      - dbslave2data:/var/lib/mysql
      - ./.docker/mysql-init/slave-init.sh:/docker-entrypoint-initdb.d/slave-init.sh:ro
    networks:
      - laravel_app_default

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - laravel_app_default

networks:
  laravel_app_default:
    external: true

volumes:
  dbmasterdata:
  dbslave1data:
  dbslave2data:
